import { Link } from "react-router-dom";
import { ArrowRight, BookOpen, CarFront, CheckCircle2, Clock3, ShieldCheck, Target } from "lucide-react";
import PublicLayout from "../components/PublicLayout";
const posts=[
 ["Defensive Driving","5 habits that make everyday city driving safer","Learn how anticipation, space and observation reduce avoidable decisions on busy roads.","https://images.pexels.com/photos/33721624/pexels-photo-33721624.jpeg?auto=compress&cs=tinysrgb&w=1400"],
 ["Beginner Guide","What to expect from your first professional lesson","A practical look at the first assessment, vehicle controls and how instructors structure early practice.","https://images.pexels.com/photos/9452104/pexels-photo-9452104.jpeg?auto=compress&cs=tinysrgb&w=1400"],
 ["Confidence","How to rebuild confidence after time away from driving","Small repeatable goals can turn hesitation into calm, consistent road behaviour.","https://images.pexels.com/photos/9827417/pexels-photo-9827417.jpeg?auto=compress&cs=tinysrgb&w=1400"],
 ["Automatic vs Manual","Which transmission training is right for you?","Understand the practical differences and choose the pathway that matches your future driving needs.","https://images.pexels.com/photos/14209232/pexels-photo-14209232.jpeg?auto=compress&cs=tinysrgb&w=1400"],
 ["Test Preparation","How to practise smarter before a driving test","Focus your final sessions on observation, positioning, manoeuvres and consistent decision-making.","https://images.pexels.com/photos/15476331/pexels-photo-15476331.jpeg?auto=compress&cs=tinysrgb&w=1400"],
 ["Road Skills","Why smooth driving is a safety skill","Controlled acceleration, braking and steering can make your intentions clearer to other road users.","https://images.pexels.com/photos/11758756/pexels-photo-11758756.jpeg?auto=compress&cs=tinysrgb&w=1600"]
];
function Rail(){return <div className="mt-8 flex snap-x gap-4 overflow-x-auto pb-3">{posts.map(([t,, ,img])=><img key={t} src={img} alt={t} className="h-44 w-[78vw] shrink-0 snap-start rounded-2xl object-cover sm:w-72"/>)}</div>}
export default function BlogPage(){return <PublicLayout><section className="public-page-hero relative overflow-hidden"><div className="absolute inset-0"><img src={posts[0][3]} alt="" className="h-full w-full object-cover opacity-25"/><div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/90 to-slate-950/60"/></div><div className="relative mx-auto max-w-[1500px] px-5 py-24 sm:px-8 lg:px-10"><p className="text-xs font-bold uppercase tracking-[.3em] text-gold-400">DriveWise Journal</p><h1 className="mt-4 max-w-4xl text-5xl font-extrabold sm:text-6xl">Practical ideas for better driving.</h1><p className="mt-5 max-w-2xl text-sm leading-7 text-slate-300">Guides, coaching insights and useful reminders for learners, licensed drivers and anyone who wants to sharpen their road skills.</p><Rail/></div></section>
<section className="mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-10"><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{posts.map(([cat,t,d,img])=><article className="glass overflow-hidden rounded-2xl" key={t}><img src={img} alt={t} className="h-52 w-full object-cover"/><div className="p-6"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-gold-400">{cat}</p><h2 className="mt-3 text-xl font-bold">{t}</h2><p className="mt-3 text-sm leading-7 text-slate-500">{d}</p><button onClick={()=>alert("This article is part of the DriveWise journal preview.")} className="mt-6 inline-flex items-center gap-2 text-xs font-bold text-gold-400">Read article <ArrowRight size={14}/></button></div></article>)}</div></section>
<section className="border-y border-white/5 bg-white/[.015]"><div className="mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-10"><p className="text-xs font-bold uppercase tracking-[.25em] text-gold-400">Featured Principles</p><h2 className="mt-3 text-3xl font-extrabold">Good driving is built from repeatable habits.</h2><div className="mt-10 grid gap-4 md:grid-cols-4">{[[ShieldCheck,"Protect space"],[Target,"Look ahead"],[CarFront,"Control inputs"],[CheckCircle2,"Finish decisions"]].map(([I,t])=><div className="glass rounded-2xl p-6" key={t}><I className="text-gold-400"/><h3 className="mt-4 font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-500">Keep the principle simple enough to apply on every journey.</p></div>)}</div></div></section>
<section className="mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-10"><div className="grid gap-8 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-gold-400">Learn With Purpose</p><h2 className="mt-3 text-3xl font-extrabold">Turn reading into practical action.</h2><p className="mt-4 text-sm leading-7 text-slate-500">Use each article as a prompt for your next lesson. Bring a question to your instructor, practise it in a controlled environment and review the result.</p><div className="mt-7 space-y-4">{["Choose one skill","Discuss it with your instructor","Practise safely","Review what changed"].map(x=><div className="flex gap-3 text-sm" key={x}><BookOpen size={17} className="text-gold-400"/>{x}</div>)}</div></div><div className="glass rounded-3xl p-8"><Clock3 className="text-gold-400"/><h3 className="mt-5 text-xl font-bold">Fresh, useful reading</h3><p className="mt-3 text-sm leading-7 text-slate-500">The journal is designed as a supporting resource alongside instructor-led training, not as a replacement for professional coaching.</p></div></div></section>
<section className="border-y border-white/5 bg-white/[.015]"><div className="mx-auto max-w-[1200px] px-5 py-20 sm:px-8"><div className="grid gap-5 md:grid-cols-3">{[["For learners","Build fundamentals and understand what to practise next."],["For licensed drivers","Refresh habits and improve confidence in changing traffic."],["For advanced drivers","Refine smoothness, anticipation and vehicle control."]].map(([t,d])=><div className="glass rounded-2xl p-7" key={t}><h3 className="font-bold">{t}</h3><p className="mt-3 text-sm leading-7 text-slate-500">{d}</p></div>)}</div></div></section>
<section className="mx-auto max-w-[1200px] px-5 py-20 text-center sm:px-8"><p className="text-xs font-bold uppercase tracking-[.25em] text-gold-400">Put It Into Practice</p><h2 className="mx-auto mt-3 max-w-3xl text-3xl font-extrabold">Have a driving goal after reading? Let's train for it.</h2><Link to="/book" className="btn-gold mt-8">Book a coaching session <ArrowRight size={16}/></Link></section>
</PublicLayout>}
