import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowRight, Award, CalendarDays, Check, CheckCircle2, Clock3, Crown, Gauge, MapPin, Menu, NotebookPen, ShieldCheck, Star, UserRound, X, Zap } from "lucide-react";
import { AnimatePresence, motion } from "framer-motion";
import { useAuth } from "../context/AuthContext";
import ThemeToggle from "../components/ThemeToggle";

const courses=[
{id:"performance",title:"Performance Driving",subtitle:"Precision & control",price:249,duration:"6 hours",badge:"Elite",image:"https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1000&q=85",description:"Advanced vehicle control, cornering technique and performance-oriented road awareness."},
{id:"automatic",title:"Executive Automatic",subtitle:"Confident daily driving",price:179,duration:"5 hours",badge:"Popular",image:"https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1000&q=85",description:"A refined automatic-driving program built around smooth control and confident urban driving."},
{id:"defensive",title:"Defensive Driving",subtitle:"Awareness & safety",price:199,duration:"5 hours",badge:"Essential",image:"https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&w=1000&q=85",description:"Hazard awareness, anticipation and safer decision-making for modern road environments."}
];
const instructors=[
{id:1,name:"Marcus Bennett",title:"Master Driving Coach",experience:"14 years",rating:4.98,reviews:284,transmission:["Automatic","Manual"],specialty:"Performance",image:"https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=85"},
{id:2,name:"Sofia Laurent",title:"Senior Driving Coach",experience:"11 years",rating:4.96,reviews:219,transmission:["Automatic"],specialty:"Executive",image:"https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=85"},
{id:3,name:"Daniel Carter",title:"Safety & Performance Coach",experience:"9 years",rating:4.94,reviews:176,transmission:["Manual","Automatic"],specialty:"Defensive",image:"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=85"}];
const slots=["08:00 AM","09:30 AM","11:00 AM","12:30 PM","02:00 PM","03:30 PM","05:00 PM","06:30 PM"];

function Logo(){return <Link to="/" className="flex items-center gap-3" aria-label="DriveWise home"><div className="flex h-10 w-10 items-center justify-center rounded-xl border border-gold-500/25 bg-gold-500/10 text-xs font-black text-gold-400">DW</div><div><p className="font-jakarta text-xs font-extrabold tracking-[0.2em]">DRIVEWISE</p><p className="text-[9px] uppercase tracking-[0.2em] text-gold-400">Executive Academy</p></div></Link>}

export default function BookingPage(){
  const navigate = useNavigate();
 const {user,logout}=useAuth(); const [step,setStep]=useState(0); const [course,setCourse]=useState(courses[0]); const [instructor,setInstructor]=useState(instructors[0]); const [transmission,setTransmission]=useState("Automatic"); const [slot,setSlot]=useState(slots[1]); const [submitted,setSubmitted]=useState(false); const [mobile,setMobile]=useState(false);
 const [details,setDetails]=useState({firstName:"",lastName:"",email:user?.email||"",phone:"",date:"",notes:""});
 const update=(k,v)=>setDetails(d=>({...d,[k]:v})); const total=useMemo(()=>course.price,[course]);
 const steps=["Course","Instructor","Details","Confirmation"];
 return <div className="booking-page min-h-screen bg-executive-950 text-white">
  <header className="sticky top-0 z-50 border-b border-white/[0.06] bg-slate-950/80 backdrop-blur-2xl"><div className="mx-auto flex h-20 max-w-[1500px] items-center justify-between px-5 sm:px-8 lg:px-10"><Logo/><nav className="hidden items-center gap-7 md:flex"><a href="#booking" className="text-sm font-semibold text-white hover:text-gold-400">Book a Session</a><a href="#experience" className="text-sm text-slate-400 hover:text-gold-400">Experience</a><a href="#support" className="text-sm text-slate-400 hover:text-gold-400">Concierge</a></nav><div className="hidden items-center gap-3 md:flex"><ThemeToggle compact/><Link to={user?.role==="admin"?"/admin":"/dashboard"} className="text-xs font-semibold text-slate-300 hover:text-gold-400">{user?.name || "Student"}</Link><img src={user?.avatar} alt={user?.name || "Student"} className="h-9 w-9 rounded-full object-cover ring-1 ring-gold-500/30"/><button onClick={logout} className="text-xs text-slate-500 hover:text-white">Sign out</button></div><button onClick={()=>setMobile(true)} className="rounded-lg border border-white/10 p-2 md:hidden"><Menu size={20}/></button></div></header>
  <AnimatePresence>{mobile&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[60] bg-slate-950/95 p-6 backdrop-blur-xl md:hidden"><div className="flex justify-between"><Logo/><button onClick={()=>setMobile(false)}><X/></button></div><div className="mt-16 space-y-6"><a href="#booking" onClick={()=>setMobile(false)} className="block text-2xl font-bold">Book a Session</a><a href="#experience" onClick={()=>setMobile(false)} className="block text-2xl text-slate-400">Experience</a><a href="#support" onClick={()=>setMobile(false)} className="block text-2xl text-slate-400">Concierge</a><Link to="/" onClick={()=>setMobile(false)} className="block text-lg font-semibold text-gold-400">Home</Link><button onClick={logout} className="text-lg font-semibold text-gold-400">Sign out</button></div></motion.div>}</AnimatePresence>
  <section className="relative overflow-hidden"><div className="absolute inset-0"><img src="https://images.unsplash.com/photo-1504215680853-026ed2a45def?auto=format&fit=crop&w=2000&q=85" alt="" className="h-full w-full object-cover opacity-25"/><div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/90 to-slate-950/55"/><div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-transparent to-slate-950"/></div><div className="ambient-gold relative mx-auto max-w-[1500px] px-5 pb-20 pt-16 sm:px-8 lg:px-10 lg:pb-24 lg:pt-24"><div className="max-w-3xl"><div className="mb-5 flex items-center gap-3 text-xs font-bold uppercase tracking-[0.3em] text-gold-400"><Crown size={15}/>Executive Driver Program</div><h1 className="font-jakarta text-4xl font-extrabold leading-tight sm:text-6xl lg:text-7xl">Your next level of<span className="text-gold-gradient"> driving.</span></h1><p className="mt-6 max-w-2xl text-sm leading-7 text-slate-300 sm:text-base">Select your program, meet your dedicated instructor and reserve a premium driving session designed around your goals.</p></div></div></section>
  <main id="booking" className="mx-auto max-w-[1500px] px-5 py-10 sm:px-8 lg:px-10 lg:py-14">
   <div className="mb-10 overflow-x-auto"><div className="flex min-w-[620px] items-center justify-between">{steps.map((s,i)=><div key={s} className="flex flex-1 items-center"><div className="flex items-center gap-3"><div className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full border text-xs font-bold ${step===i?"border-gold-400 bg-gold-500 text-slate-950":step>i?"border-gold-500/50 bg-gold-500/10 text-gold-400":"border-white/10 bg-white/[0.03] text-slate-500"}`}>{step>i?<Check size={15}/>:`0${i+1}`}</div><div><p className="text-xs font-bold">{s}</p><p className="hidden text-[10px] text-slate-600 sm:block">{["Choose your program","Expert & schedule","Your information","Review & confirm"][i]}</p></div></div>{i<3&&<div className="mx-5 h-px flex-1 bg-white/10"/>}</div>)}</div></div>
   <AnimatePresence mode="wait">
    {step===0&&<motion.div key="course" initial={{opacity:0,x:15}} animate={{opacity:1,x:0}}><Header step="01" title="Select your driving program" sub="Every program is delivered by a certified DriveWise professional."/><div className="grid gap-5 lg:grid-cols-3">{courses.map(c=><button key={c.id} onClick={()=>setCourse(c)} className={`group overflow-hidden rounded-2xl text-left ${course.id===c.id?"glass glass-gold ring-1 ring-gold-500/40":"glass hover:border-white/15"}`}><div className="relative h-56 overflow-hidden"><img src={c.image} alt={c.title} className="h-full w-full object-cover transition duration-700 group-hover:scale-110"/><div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-transparent to-transparent"/><span className="absolute left-4 top-4 rounded-full border border-gold-500/20 bg-slate-950/70 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-gold-400">{c.badge}</span>{course.id===c.id&&<div className="absolute right-4 top-4 flex h-8 w-8 items-center justify-center rounded-full bg-gold-500 text-slate-950"><Check size={15}/></div>}</div><div className="p-5"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-gold-400">{c.subtitle}</p><h3 className="mt-2 text-lg font-bold">{c.title}</h3><p className="mt-2 min-h-[48px] text-sm leading-6 text-slate-500">{c.description}</p><div className="mt-5 flex items-end justify-between border-t border-white/5 pt-5"><div><p className="text-xs text-slate-500">Program fee</p><p className="mt-1 text-xl font-extrabold">${c.price}</p></div><div className="text-right"><p className="text-xs text-slate-500">Duration</p><p className="mt-1 text-xs font-semibold">{c.duration}</p></div></div></div></button>)}</div></motion.div>}
    {step===1&&<motion.div key="instructor" initial={{opacity:0,x:15}} animate={{opacity:1,x:0}}><Header step="02" title="Choose your instructor" sub="Pair your selected program with an expert instructor."/><div className="grid gap-5 xl:grid-cols-3">{instructors.map(x=><button key={x.id} onClick={()=>{setInstructor(x);if(!x.transmission.includes(transmission))setTransmission(x.transmission[0])}} className={`glass rounded-2xl p-5 text-left ${instructor.id===x.id?"glass-gold ring-1 ring-gold-500/40":""}`}><div className="flex gap-4"><img src={x.image} alt={x.name} className="h-20 w-20 rounded-2xl object-cover"/><div><h3 className="font-bold">{x.name}</h3><p className="mt-1 text-xs text-slate-500">{x.title}</p><div className="mt-3 flex items-center gap-1"><Star size={13} fill="currentColor" className="text-gold-400"/><span className="text-xs font-bold">{x.rating}</span><span className="text-[10px] text-slate-600">({x.reviews})</span></div></div></div><div className="mt-5 flex justify-between border-t border-white/5 pt-4"><span className="rounded-full border border-white/10 px-3 py-1 text-[10px] text-slate-400">{x.experience} experience</span><span className="text-[10px] font-bold uppercase tracking-wider text-gold-400">{x.specialty}</span></div></button>)}</div><div className="mt-7 grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><div className="glass rounded-2xl p-6"><div className="mb-5 flex items-center gap-3"><Gauge size={18} className="text-gold-400"/><h3 className="text-sm font-bold">Transmission</h3></div><div className="grid grid-cols-2 rounded-xl border border-white/10 bg-slate-950/50 p-1">{["Automatic","Manual"].map(o=><button key={o} disabled={!instructor.transmission.includes(o)} onClick={()=>setTransmission(o)} className={`rounded-lg px-4 py-3 text-xs font-bold ${transmission===o?"bg-gold-500 text-slate-950":"text-slate-500"} disabled:cursor-not-allowed disabled:opacity-30`}>{o}</button>)}</div><div className="mt-5 rounded-xl border border-gold-500/10 bg-gold-500/[0.04] p-4 text-xs leading-5 text-slate-500"><ShieldCheck size={16} className="mr-2 inline text-gold-400"/>Vehicle allocation is subject to instructor and fleet availability.</div></div><div className="glass rounded-2xl p-6"><div className="mb-5 flex items-center gap-3"><CalendarDays size={18} className="text-gold-400"/><h3 className="text-sm font-bold">Choose a time</h3></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{slots.map(s=><button key={s} onClick={()=>setSlot(s)} className={`rounded-xl border px-3 py-3 text-xs font-semibold ${slot===s?"border-gold-500/50 bg-gold-500/10 text-gold-400":"border-white/10 bg-white/[0.02] text-slate-500"}`}>{s}</button>)}</div></div></div></motion.div>}
    {step===2&&<motion.div key="details" initial={{opacity:0,x:15}} animate={{opacity:1,x:0}}><Header step="03" title="Tell us about yourself" sub="Your information helps us personalize the session."/><div className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><div className="glass rounded-2xl p-6 sm:p-8"><div className="grid gap-5 sm:grid-cols-2">{[["firstName","First Name","Alexander"],["lastName","Last Name","Morgan"],["email","Email","you@example.com"],["phone","Phone Number","+1 555 000 0000"]].map(([k,l,p])=><div key={k}><label className="mb-2 block text-xs font-semibold text-slate-400">{l}</label><input type={k==="email"?"email":"text"} className="executive-input" placeholder={p} value={details[k]} onChange={e=>update(k,e.target.value)}/></div>)}<div className="sm:col-span-2"><label className="mb-2 block text-xs font-semibold text-slate-400">Preferred Date</label><input type="date" className="executive-input" value={details.date} onChange={e=>update("date",e.target.value)}/></div><div className="sm:col-span-2"><label className="mb-2 block text-xs font-semibold text-slate-400">Instructor Notes</label><textarea rows="5" className="executive-input resize-none" placeholder="Tell your instructor about your goals..." value={details.notes} onChange={e=>update("notes",e.target.value)}/></div></div></div><Summary course={course} instructor={instructor} transmission={transmission} slot={slot}/></div></motion.div>}
    {step===3&&<motion.div key="confirmation" initial={{opacity:0,x:15}} animate={{opacity:1,x:0}}>{submitted?<div className="mx-auto max-w-2xl text-center"><div className="glass glass-gold rounded-3xl p-10 sm:p-14"><motion.div initial={{scale:0}} animate={{scale:1}} className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-gold-500 text-slate-950 shadow-goldStrong"><CheckCircle2 size={38}/></motion.div><p className="mt-8 text-xs font-bold uppercase tracking-[0.3em] text-gold-400">Reservation confirmed</p><h2 className="mt-3 font-jakarta text-3xl font-extrabold sm:text-4xl">Your session is reserved.</h2><p className="mx-auto mt-5 max-w-lg text-sm leading-7 text-slate-500">Your DriveWise executive session has been successfully scheduled.</p><button onClick={()=>{setSubmitted(false);setStep(0)}} className="btn-gold mt-8">Book Another Session</button></div></div>:<><Header step="04" title="Review your reservation" sub="Everything looks good? Confirm your executive driving session."/><div className="grid gap-6 lg:grid-cols-[1.15fr_0.85fr]"><div className="glass overflow-hidden rounded-2xl"><img src={course.image} alt={course.title} className="h-64 w-full object-cover"/><div className="grid gap-4 p-6 sm:grid-cols-2">{[[Clock3,"Scheduled",slot],[CalendarDays,"Date",details.date||"Sep 04, 2026"],[UserRound,"Instructor",instructor.name],[Gauge,"Vehicle",transmission]].map(([I,l,v])=><div key={l} className="flex gap-3 rounded-xl border border-white/5 bg-white/[0.025] p-4"><I size={18} className="text-gold-400"/><div><p className="text-[10px] uppercase tracking-wider text-slate-600">{l}</p><p className="mt-1 text-sm font-bold">{v}</p></div></div>)}</div><div className="border-t border-white/5 p-6"><MapPin size={18} className="mr-2 inline text-gold-400"/><span className="text-xs font-bold">DriveWise Executive Center</span></div></div><div className="glass glass-gold h-fit rounded-2xl p-6"><div className="flex items-center gap-3"><NotebookPen size={18} className="text-gold-400"/><h3 className="font-bold">Executive receipt</h3></div><div className="my-6 flex justify-between text-sm"><span className="text-slate-500">{course.title}</span><span className="font-semibold">${total}</span></div><div className="border-t border-white/10 pt-5"><p className="text-xs text-slate-500">Total</p><p className="mt-1 text-3xl font-extrabold text-gold-400">${total}</p></div><button onClick={()=>navigate(`/payment?booking=DW-${Date.now().toString().slice(-5)}&course=${encodeURIComponent(course.title)}&instructor=${encodeURIComponent(instructor.name)}&date=${encodeURIComponent(details.date||"Sep 04, 2026")}&time=${encodeURIComponent(slot)}&amount=${total}`)} className="btn-gold mt-7 w-full">Proceed to Payment<Check size={17}/></button></div></div></>}</motion.div>}
   </AnimatePresence>
   {!submitted&&<div className="mt-10 flex justify-between border-t border-white/5 pt-6"><button onClick={()=>setStep(s=>Math.max(0,s-1))} disabled={step===0} className="btn-secondary disabled:opacity-20"><ArrowLeft size={16}/>Back</button>{step<3&&<button onClick={()=>setStep(s=>Math.min(3,s+1))} className="btn-gold">Continue<ArrowRight size={16}/></button>}</div>}
  </main>
  <section id="experience" className="border-t border-white/5"><div className="mx-auto max-w-[1500px] px-5 py-14 sm:px-8 lg:px-10"><div className="mb-8"><p className="text-xs font-bold uppercase tracking-[0.25em] text-gold-400">The DriveWise experience</p><h2 className="mt-2 font-jakarta text-3xl font-extrabold">Built around confidence, precision and care.</h2></div><div className="grid gap-5 md:grid-cols-3">{[[Award,"Certified Excellence","Learn from instructors selected for expertise, communication and road safety."],[Zap,"Precision Scheduling","Choose your preferred time and build your driving development around your schedule."],[ShieldCheck,"Executive Concierge","Our academy team is available to help tailor your experience."]].map(([I,t,d])=><div key={t} className="glass rounded-2xl p-6"><I size={21} className="text-gold-400"/><h3 className="mt-5 font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{d}</p></div>)}</div></div></section><section id="support" className="border-t border-white/5"><div className="mx-auto max-w-[1500px] px-5 py-14 sm:px-8 lg:px-10"><div className="grid gap-6 lg:grid-cols-[1fr_0.8fr]"><div><p className="text-xs font-bold uppercase tracking-[0.25em] text-gold-400">Concierge</p><h2 className="mt-2 font-jakarta text-3xl font-extrabold">Need help choosing your session?</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-500">Our concierge team can help with course selection, instructor matching, schedule changes and special training requests.</p></div><div className="glass glass-gold rounded-2xl p-6"><p className="text-sm font-bold">DriveWise Executive Concierge</p><p className="mt-2 text-sm text-slate-500">+1 555 018 2026 · concierge@drivewise.example</p><div className="mt-5 flex flex-wrap gap-3"><a href="tel:+15550182026" className="btn-gold text-xs">Call concierge</a><a href="mailto:concierge@drivewise.example" className="btn-secondary text-xs">Email concierge</a><Link to="/contact" className="btn-secondary text-xs">Contact page</Link></div></div></div></div></section>
 </div>
}

function Header({step,title,sub}){return <div className="mb-7"><p className="text-xs font-bold uppercase tracking-[0.25em] text-gold-400">Step {step}</p><h2 className="mt-2 font-jakarta text-2xl font-extrabold sm:text-3xl">{title}</h2><p className="mt-2 text-sm text-slate-500">{sub}</p></div>}
function Summary({course,instructor,transmission,slot}){return <div className="glass glass-gold h-fit rounded-2xl p-6"><p className="text-xs font-bold uppercase tracking-[0.2em] text-gold-400">Your selection</p><div className="mt-5 flex gap-4"><img src={instructor.image} alt={instructor.name} className="h-16 w-16 rounded-xl object-cover"/><div><p className="font-bold">{instructor.name}</p><p className="mt-1 text-xs text-slate-500">{instructor.title}</p></div></div><div className="my-5 h-px bg-white/10"/><div className="space-y-4 text-sm"><div className="flex justify-between"><span className="text-slate-500">Program</span><span className="font-semibold">{course.title}</span></div><div className="flex justify-between"><span className="text-slate-500">Transmission</span><span className="font-semibold">{transmission}</span></div><div className="flex justify-between"><span className="text-slate-500">Time</span><span className="font-semibold">{slot}</span></div></div></div>}