import { Link } from "react-router-dom";
import { ArrowRight, Award, CheckCircle2, ShieldCheck, Star, Users, Zap } from "lucide-react";
import { motion } from "framer-motion";
import PublicLayout from "../components/PublicLayout";

const courses=[
["Performance Driving","Advanced vehicle control, precision cornering and confidence.","$249","6 hours","https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1000&q=85"],
["Executive Automatic","Smooth, confident automatic driving for modern city and highway environments.","$179","5 hours","https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1000&q=85"],
["Defensive Driving","Hazard awareness, anticipation and safer decision-making.","$199","5 hours","https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&w=1000&q=85"]
];
export default function HomePage(){return <PublicLayout>
<section className="public-image-hero relative min-h-[720px] overflow-hidden"><img src="https://images.unsplash.com/photo-1504215680853-026ed2a45def?auto=format&fit=crop&w=2200&q=90" className="absolute inset-0 h-full w-full object-cover opacity-40" alt="Luxury driving road"/><div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/85 to-slate-950/35"/><div className="absolute inset-0 bg-gradient-to-t from-slate-950 to-transparent"/>
<div className="relative mx-auto flex min-h-[720px] max-w-[1500px] items-center px-5 py-24 sm:px-8 lg:px-10"><div className="max-w-3xl"><p className="mb-5 text-xs font-bold uppercase tracking-[0.35em] text-gold-400">Elite Driver Education · Since 2012</p><h1 className="font-jakarta text-5xl font-extrabold leading-[1.05] sm:text-7xl">Drive with <span className="text-gold-gradient">confidence.</span><br/>Arrive with control.</h1><p className="mt-7 max-w-2xl text-base leading-8 text-slate-300">DriveWise Academy delivers premium, structured driver training for beginners, experienced motorists and executive clients who expect more from every mile.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/book" className="btn-gold">Book a session <ArrowRight size={17}/></Link><Link to="/courses" className="btn-secondary">Explore courses</Link></div><div className="mt-12 flex flex-wrap gap-8 text-xs text-slate-400"><span><b className="text-white">12+</b> years experience</span><span><b className="text-white">98.7%</b> pass rate</span><span><b className="text-white">24</b> certified instructors</span></div></div></div></section>
<section className="mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-10"><div className="mb-10 max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.25em] text-gold-400">Signature Programs</p><h2 className="mt-3 font-jakarta text-3xl font-extrabold sm:text-4xl">Training built around your goals.</h2></div><div className="grid gap-5 lg:grid-cols-3">{courses.map((c,i)=><motion.article whileHover={{y:-5}} key={c[0]} className="glass overflow-hidden rounded-2xl"><img src={c[4]} alt={c[0]} className="h-56 w-full object-cover"/><div className="p-6"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-gold-400">{c[3]} · from {c[2]}</p><h3 className="mt-2 text-xl font-bold">{c[0]}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{c[1]}</p><Link to="/book" className="mt-5 inline-flex items-center gap-2 text-xs font-bold text-gold-400">Reserve this course <ArrowRight size={14}/></Link></div></motion.article>)}</div></section>
<section className="border-y border-white/5 bg-white/[0.015]"><div className="mx-auto grid max-w-[1500px] gap-6 px-5 py-20 sm:px-8 md:grid-cols-4 lg:px-10">{[[ShieldCheck,"Safety-first methodology","Structured lessons, hazard awareness and road-ready decision making."],[Award,"Certified coaches","Experienced instructors selected for expertise, communication and patience."],[Zap,"Flexible scheduling","Choose instructor, date and time around your personal schedule."],[Users,"Personal progress","Track completed sessions, milestones and next training recommendations."]].map(([I,t,d])=><div key={t} className="glass rounded-2xl p-6"><I className="text-gold-400" size={22}/><h3 className="mt-5 font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{d}</p></div>)}</div></section>
<section className="mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-10"><div className="grid gap-8 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[0.25em] text-gold-400">Why DriveWise</p><h2 className="mt-3 font-jakarta text-3xl font-extrabold">A modern standard for driver development.</h2><p className="mt-5 text-sm leading-7 text-slate-500">Our methodology blends practical road time with clear coaching, measurable milestones and safety standards designed to build habits that last beyond the test.</p><div className="mt-7 space-y-4">{["Individual learning plans","Automatic and manual instruction","Vehicle and instructor matching","Transparent pricing and payment tracking"].map(x=><div key={x} className="flex items-center gap-3 text-sm"><CheckCircle2 size={17} className="text-gold-400"/>{x}</div>)}</div></div><div className="glass rounded-3xl p-8"><Star className="text-gold-400" fill="currentColor"/><p className="mt-6 text-xl font-semibold leading-8">“The coaching felt personal, structured and genuinely premium. I left every session knowing exactly what to improve next.”</p><div className="mt-7 text-xs text-slate-500">— Daniel, Executive Automatic graduate</div></div></div></section>
<section className="relative overflow-hidden border-t border-white/5"><div className="absolute inset-0 bg-gold-500/[0.03]"/><div className="relative mx-auto max-w-[1500px] px-5 py-20 text-center sm:px-8"><p className="text-xs font-bold uppercase tracking-[0.25em] text-gold-400">Start your journey</p><h2 className="mx-auto mt-3 max-w-3xl font-jakarta text-4xl font-extrabold">Your next level of driving starts with one session.</h2><Link to="/book" className="btn-gold mt-8">Book your first session <ArrowRight size={17}/></Link></div></section>
</PublicLayout>}
