import { Link } from "react-router-dom";
import { ArrowRight, CheckCircle2, Clock3, ShieldCheck, Star, Target, Users } from "lucide-react";
import { motion } from "framer-motion";
import PublicLayout from "../components/PublicLayout";

const images = [
  "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1000&q=85",
  "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1000&q=85",
  "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&w=1000&q=85",
  "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1000&q=85",
];

function Rail() { return <div className="mt-8 flex snap-x gap-4 overflow-x-auto pb-3 scrollbar-thin">{images.map((src,i)=><img key={src} src={src} alt={`DriveWise training ${i+1}`} className="h-44 w-[76vw] shrink-0 snap-start rounded-2xl object-cover sm:w-72" />)}</div>; }

export default function Home2Page() {
 return <PublicLayout><section className="public-image-hero relative overflow-hidden"><img src={images[0]} alt="DriveWise vehicle" className="absolute inset-0 h-full w-full object-cover opacity-35"/><div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/85 to-slate-950/40"/><div className="relative mx-auto max-w-[1500px] px-5 py-24 sm:px-8 lg:px-10"><p className="text-xs font-bold uppercase tracking-[.3em] text-gold-400">Home 02 · Precision & Confidence</p><h1 className="mt-4 max-w-4xl text-5xl font-extrabold sm:text-7xl">Your next level of driving starts here.</h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-300">A premium training experience for people who want calm decision-making, stronger vehicle control and a clear path from practice to independence.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/book" className="btn-gold">Start your journey <ArrowRight size={16}/></Link><Link to="/services" className="btn-secondary">Explore services</Link></div><Rail/></div></section>
 {/*2*/}<section className="mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-10"><div className="grid gap-5 md:grid-cols-3">{[[ShieldCheck,"Safety architecture","Every lesson reinforces observation, anticipation, space management and responsible road decisions."],[Target,"Goal-based coaching","Training plans are shaped around your experience, transmission preference and real-world driving needs."],[Users,"Personal attention","Small, focused sessions give you space to ask questions, practise repeatedly and receive useful feedback."]].map(([I,t,d])=><div className="glass rounded-2xl p-7" key={t}><I className="text-gold-400"/><h2 className="mt-5 text-xl font-bold">{t}</h2><p className="mt-3 text-sm leading-7 text-slate-500">{d}</p></div>)}</div></section>
 {/*3*/}<section className="border-y border-white/5 bg-white/[.015]"><div className="mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-10"><p className="text-xs font-bold uppercase tracking-[.25em] text-gold-400">Choose Your Focus</p><h2 className="mt-3 text-3xl font-extrabold">A pathway for every stage.</h2><div className="mt-10 grid gap-5 lg:grid-cols-4">{[["Beginner","Build the fundamentals"],["Refresher","Restore confidence"],["Advanced","Sharpen control"],["Executive","Drive smoothly on demanding schedules"]].map(([t,d])=><motion.div whileHover={{y:-4}} key={t} className="glass rounded-2xl p-6"><span className="text-[10px] font-bold uppercase tracking-wider text-gold-400">Program</span><h3 className="mt-4 font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{d}</p><Link to="/courses" className="mt-5 inline-flex items-center gap-2 text-xs font-bold text-gold-400">View pathway <ArrowRight size={14}/></Link></motion.div>)}</div></div></section>
 {/*4*/}<section className="mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-10"><div className="grid gap-8 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-gold-400">The Session Standard</p><h2 className="mt-3 text-3xl font-extrabold">Learn, practise, review, repeat.</h2><div className="mt-8 space-y-5">{[["01","Brief","Set the objective and understand the skill."],["02","Drive","Practise with instructor guidance in realistic conditions."],["03","Review","Identify strengths, risks and the next improvement."],["04","Plan","Leave with a practical target for the next session."]].map(([n,t,d])=><div className="flex gap-4" key={n}><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-gold-500/10 text-xs font-bold text-gold-400">{n}</span><div><h3 className="font-bold">{t}</h3><p className="mt-1 text-sm leading-6 text-slate-500">{d}</p></div></div>)}</div></div><div className="glass overflow-hidden rounded-3xl"><img src={images[1]} alt="Student driving" className="h-full min-h-[430px] w-full object-cover"/></div></div></section>
 {/*5*/}<section className="border-y border-white/5 bg-white/[.015]"><div className="mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-10"><div className="grid gap-6 md:grid-cols-3">{[["4.9/5","Student satisfaction"],["98.7%","Reported pass rate"],["12+","Years of experience"]].map(([v,l])=><div className="glass rounded-2xl p-7 text-center" key={l}><p className="text-4xl font-extrabold text-gold-400">{v}</p><p className="mt-2 text-xs uppercase tracking-wider text-slate-500">{l}</p></div>)}</div><Rail/></div></section>
 {/*6*/}<section className="mx-auto max-w-[1500px] px-5 py-20 text-center sm:px-8 lg:px-10"><Star className="mx-auto text-gold-400" fill="currentColor"/><h2 className="mx-auto mt-5 max-w-3xl text-3xl font-extrabold">Make your next mile a more confident one.</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-7 text-slate-500">Explore the academy, choose a service and reserve a session that fits your goals.</p><Link to="/book" className="btn-gold mt-8">Book DriveWise <ArrowRight size={16}/></Link></section>
 </PublicLayout>
}
