import { Link } from "react-router-dom";
import { ArrowRight, Award, CarFront, CheckCircle2, Clock3, Mail, MapPin, Phone, ShieldCheck, Star, Target, Users, Zap } from "lucide-react";
import PublicLayout from "../components/PublicLayout";

const courseData = [
  ["Beginner Driving Course", "Build a strong foundation from cockpit controls through independent road driving.", "$159", "4 hours", "Foundation"],
  ["Advanced Driving Course", "Refine observation, lane discipline, highway confidence and advanced vehicle control.", "$299", "8 hours", "Advanced"],
  ["Refresher Course", "Focused coaching for licensed drivers returning to the road or rebuilding confidence.", "$129", "2 hours", "Flexible"],
  ["Automatic Training", "Smooth acceleration, braking, positioning and modern automatic vehicle confidence.", "$179", "5 hours", "Popular"],
  ["Manual Training", "Clutch control, gear selection, hill starts and confident manual road technique.", "$189", "5 hours", "Classic"]
];

const pageImageSets = {
  "About DriveWise": [
    "https://images.unsplash.com/photo-1694725728902-c5e8e3cda091?auto=format&fit=crop&w=1600&q=85",
    "https://images.unsplash.com/photo-1606222168004-4d6be3da75d4?auto=format&fit=crop&w=1600&q=85",
    "https://images.unsplash.com/photo-1694725736570-e2343ab54550?auto=format&fit=crop&w=1600&q=85"
],
  "Driving Courses": [
    "https://images.pexels.com/photos/17918280/pexels-photo-17918280.jpeg?auto=compress&cs=tinysrgb&w=1400",
    "https://images.pexels.com/photos/5556538/pexels-photo-5556538.jpeg?auto=compress&cs=tinysrgb&w=1400",
    "https://images.pexels.com/photos/27591711/pexels-photo-27591711.jpeg?auto=compress&cs=tinysrgb&w=1400"
],
  "Meet Your Coaches": [
    "https://images.pexels.com/photos/12905858/pexels-photo-12905858.jpeg?auto=compress&cs=tinysrgb&w=1400",
    "https://images.pexels.com/photos/10394781/pexels-photo-10394781.jpeg?auto=compress&cs=tinysrgb&w=1400",
    "https://images.pexels.com/photos/22039971/pexels-photo-22039971.jpeg?auto=compress&cs=tinysrgb&w=1400"
],
  "Pricing & Packages": [
    "https://images.pexels.com/photos/12964189/pexels-photo-12964189.jpeg?auto=compress&cs=tinysrgb&w=1400",
    "https://images.pexels.com/photos/5120108/pexels-photo-5120108.jpeg?auto=compress&cs=tinysrgb&w=1400",
    "https://images.pexels.com/photos/7839729/pexels-photo-7839729.jpeg?auto=compress&cs=tinysrgb&w=1400"
],
  "Concierge & Enquiry": [
    "https://images.pexels.com/photos/30195132/pexels-photo-30195132.jpeg?auto=compress&cs=tinysrgb&w=1400",
    "https://images.pexels.com/photos/33253286/pexels-photo-33253286.jpeg?auto=compress&cs=tinysrgb&w=1400",
    "https://images.pexels.com/photos/32362622/pexels-photo-32362622.jpeg?auto=compress&cs=tinysrgb&w=1400"
]
};

function PageHero({ eyebrow, title, desc, image }) {
  const gallery = pageImageSets[eyebrow] || (image ? [image] : []);
  return <section className="public-page-hero relative overflow-hidden border-b border-white/5"><div className="absolute inset-0">{image && <img src={image} className="h-full w-full object-cover opacity-25" alt="" />}<div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/90 to-slate-950/65" /></div><div className="relative mx-auto max-w-[1500px] px-5 py-24 sm:px-8 lg:px-10"><p className="text-xs font-bold uppercase tracking-[0.3em] text-gold-400">{eyebrow}</p><h1 className="mt-4 max-w-4xl font-jakarta text-4xl font-extrabold sm:text-6xl">{title}</h1><p className="mt-5 max-w-2xl text-sm leading-7 text-slate-300">{desc}</p><div className="mt-8 flex snap-x gap-4 overflow-x-auto pb-2">{gallery.map((src, i) => <img key={src} src={src} alt={`${eyebrow} visual ${i + 1}`} className="h-28 w-56 shrink-0 snap-start rounded-xl object-cover ring-1 ring-white/10 sm:h-32 sm:w-64" />)}</div></div></section>;
}

export function AboutPage() { return <PublicLayout><PageHero eyebrow="About DriveWise" title="A smarter, safer way to learn to drive." desc="DriveWise Academy combines experienced instructors, structured methodology and premium service to help every student become a capable, responsible driver." image="https://images.unsplash.com/photo-1694725728902-c5e8e3cda091?auto=format&fit=crop&w=1600&q=85" />
  {/* 2 */}<section className="mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-10"><div className="grid gap-6 lg:grid-cols-2"><div className="glass rounded-2xl p-8"><Target className="text-gold-400" /><h2 className="mt-5 text-2xl font-bold">Mission & Vision</h2><p className="mt-4 text-sm leading-7 text-slate-500">Our mission is to develop calm, observant and confident drivers through practical coaching. Our vision is a road culture where safety, courtesy and skill are standard for every driver.</p></div><div className="glass rounded-2xl p-8"><ShieldCheck className="text-gold-400" /><h2 className="mt-5 text-2xl font-bold">Safety Standards</h2><p className="mt-4 text-sm leading-7 text-slate-500">Lessons emphasize defensive habits, hazard anticipation, vehicle checks, safe positioning and responsible decision-making in real road conditions.</p></div></div></section>
  {/* 3 */}<section className="border-y border-white/5 bg-white/[0.015]"><div className="mx-auto grid max-w-[1500px] gap-5 px-5 py-16 sm:px-8 md:grid-cols-4 lg:px-10">{[["12+","Years operating"],["24","Certified instructors"],["98.7%","Reported pass rate"],["4.9/5","Student satisfaction"]].map(([v,l])=><div className="glass rounded-2xl p-7 text-center" key={l}><p className="text-3xl font-extrabold text-gold-400">{v}</p><p className="mt-2 text-sm text-slate-500">{l}</p></div>)}</div></section>
  {/* 4 */}<section className="mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-10"><div className="grid gap-8 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[0.25em] text-gold-400">How We Teach</p><h2 className="mt-3 text-3xl font-extrabold">A four-stage methodology that keeps progress visible.</h2><div className="mt-8 space-y-6">{[["01","Assess","Understand your starting point, confidence level and goals."],["02","Coach","Explain the technique clearly and demonstrate the correct approach."],["03","Practice","Build repeatable habits through guided road time and realistic scenarios."],["04","Progress","Review results, document milestones and set the next training objective."]].map(([n,t,d])=><div className="flex gap-4" key={n}><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-gold-500/10 text-xs font-bold text-gold-400">{n}</span><div><h3 className="font-bold">{t}</h3><p className="mt-1 text-sm leading-6 text-slate-500">{d}</p></div></div>)}</div></div><div className="glass overflow-hidden rounded-3xl"><img src="https://images.unsplash.com/photo-1606222168004-4d6be3da75d4?auto=format&fit=crop&w=1600&q=85" className="h-full min-h-[420px] w-full object-cover" alt="DriveWise training vehicle" /></div></div></section>
  {/* 5 */}<section className="border-y border-white/5 bg-white/[0.015]"><div className="mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-10"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.25em] text-gold-400">What Students Can Expect</p><h2 className="mt-3 text-3xl font-extrabold">Professional service from the first enquiry to the final lesson.</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3">{[[Users,"Personalized coaching","Lessons adapt to your pace, experience, transmission and goals."],[Clock3,"Reliable scheduling","Choose practical slots and keep upcoming sessions visible in your dashboard."],[Award,"Continuous improvement","Feedback is focused on specific road skills rather than generic instruction."]].map(([I,t,d])=><div className="glass rounded-2xl p-7" key={t}><I className="text-gold-400" /><h3 className="mt-5 font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{d}</p></div>)}</div></div></section>
  {/* 6 */}<section className="mx-auto max-w-[1500px] px-5 py-20 text-center sm:px-8 lg:px-10"><p className="text-xs font-bold uppercase tracking-[0.25em] text-gold-400">Ready to begin?</p><h2 className="mx-auto mt-3 max-w-3xl text-3xl font-extrabold sm:text-4xl">Start with a conversation, assessment or your first driving session.</h2><div className="mt-8 flex flex-wrap justify-center gap-3"><Link to="/book" className="btn-gold">Book a session <ArrowRight size={16} /></Link><Link to="/contact" className="btn-secondary">Talk to our team</Link></div></section>
</PublicLayout>; }

export function CoursesPage() { return <PublicLayout><PageHero eyebrow="Driving Courses" title="Programs for every stage of your driving journey." desc="From first-time learners to experienced drivers seeking sharper control, choose a program designed around measurable progress." image="https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&w=1800&q=85" />
  {/* 2 */}<section className="mx-auto max-w-[1500px] px-5 py-16 sm:px-8 lg:px-10"><div className="grid gap-5 lg:grid-cols-3">{courseData.map((c) => <div key={c[0]} className="glass rounded-2xl p-7"><span className="rounded-full border border-gold-500/20 bg-gold-500/5 px-3 py-1 text-[9px] font-bold uppercase tracking-wider text-gold-400">{c[4]}</span><h2 className="mt-5 text-xl font-bold">{c[0]}</h2><p className="mt-3 min-h-[72px] text-sm leading-6 text-slate-500">{c[1]}</p><div className="mt-6 flex justify-between border-t border-white/5 pt-5"><div><p className="text-[10px] text-slate-600">Price</p><p className="text-xl font-extrabold">{c[2]}</p></div><div className="text-right"><p className="text-[10px] text-slate-600">Duration</p><p className="text-sm font-bold">{c[3]}</p></div></div><Link to="/book" className="btn-gold mt-6 w-full text-xs">Book course <ArrowRight size={15} /></Link></div>)}</div></section>
  {/* 3 */}<section className="border-y border-white/5 bg-white/[0.015]"><div className="mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-10"><div className="grid gap-6 lg:grid-cols-2"><div className="glass rounded-2xl p-8"><CarFront className="text-gold-400" /><h2 className="mt-5 text-2xl font-bold">Automatic Training</h2><p className="mt-3 text-sm leading-7 text-slate-500">Build smooth acceleration, controlled braking, lane positioning, mirror routines and confident city/highway driving in a modern automatic vehicle.</p><ul className="mt-5 space-y-3 text-sm text-slate-400">{["Traffic awareness","Parking and manoeuvring","Highway confidence","Smooth vehicle control"].map(x=><li key={x} className="flex gap-2"><CheckCircle2 size={16} className="text-gold-400" />{x}</li>)}</ul></div><div className="glass rounded-2xl p-8"><Zap className="text-gold-400" /><h2 className="mt-5 text-2xl font-bold">Manual Training</h2><p className="mt-3 text-sm leading-7 text-slate-500">Develop clutch control, gear selection, hill starts, smooth changes and reliable manual driving habits in real traffic conditions.</p><ul className="mt-5 space-y-3 text-sm text-slate-400">{["Clutch bite-point control","Gear selection","Hill starts","Stop-and-go traffic"].map(x=><li key={x} className="flex gap-2"><CheckCircle2 size={16} className="text-gold-400" />{x}</li>)}</ul></div></div></div></section>
  {/* 4 */}<section className="mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-10"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.25em] text-gold-400">What You Learn</p><h2 className="mt-3 text-3xl font-extrabold">Skills that matter beyond the driving test.</h2><p className="mt-4 text-sm leading-7 text-slate-500">Our courses cover the practical behaviors that help drivers remain composed and predictable in everyday road situations.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[ShieldCheck,"Hazard awareness"],[Target,"Observation"],[CarFront,"Vehicle control"],[Users,"Road courtesy"]].map(([I,t])=><div className="glass rounded-2xl p-6" key={t}><I className="text-gold-400" /><h3 className="mt-4 font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-500">Practical coaching and feedback are built into every pathway.</p></div>)}</div></section>
  {/* 5 */}<section className="border-y border-white/5 bg-white/[0.015]"><div className="mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-10"><div className="grid gap-8 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[0.25em] text-gold-400">Course Planning</p><h2 className="mt-3 text-3xl font-extrabold">Not sure which program is right?</h2><p className="mt-4 text-sm leading-7 text-slate-500">Start with your experience level, driving goals and preferred transmission. Our booking flow helps you choose a suitable instructor and session time.</p><div className="mt-7 space-y-3">{["New driver → Beginner","Licensed but out of practice → Refresher","Confident driver → Advanced","Automatic preference → Automatic Training","Manual preference → Manual Training"].map(x=><div key={x} className="flex items-center gap-3 text-sm"><CheckCircle2 size={16} className="text-gold-400" />{x}</div>)}</div></div><div className="glass rounded-3xl p-8"><Clock3 className="text-gold-400" /><h3 className="mt-5 text-xl font-bold">Flexible session lengths</h3><p className="mt-3 text-sm leading-7 text-slate-500">Choose a focused 2-hour refresher or a longer structured pathway. Package options are available for students who want consistent weekly progress.</p><Link to="/pricing" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-gold-400">See packages <ArrowRight size={15} /></Link></div></div></div></section>
  {/* 6 */}<section className="mx-auto max-w-[1500px] px-5 py-20 text-center sm:px-8 lg:px-10"><p className="text-xs font-bold uppercase tracking-[0.25em] text-gold-400">Choose Your Path</p><h2 className="mx-auto mt-3 max-w-3xl text-3xl font-extrabold">Turn your next lesson into measurable progress.</h2><Link to="/book" className="btn-gold mt-8">Book a course <ArrowRight size={16} /></Link></section>
</PublicLayout>; }

export function InstructorsPage() { const people = [["Marcus Bennett","Master Driving Coach","14 years","4.98","Performance","https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=500&q=85"],["Sofia Laurent","Senior Driving Coach","11 years","4.96","Executive","https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=500&q=85"],["Daniel Carter","Safety & Performance Coach","9 years","4.94","Defensive","https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=85"]]; return <PublicLayout><PageHero eyebrow="Meet Your Coaches" title="Experienced instructors who teach with clarity." desc="Every coach is selected for expertise, patience, communication and commitment to safe road behavior." />
  {/* 2 */}<section className="mx-auto max-w-[1500px] px-5 py-16 sm:px-8 lg:px-10"><div className="grid gap-6 md:grid-cols-3">{people.map(p=><article className="glass overflow-hidden rounded-2xl" key={p[0]}><img src={p[5]} className="h-72 w-full object-cover" alt={p[0]} /><div className="p-6"><h2 className="text-xl font-bold">{p[0]}</h2><p className="mt-1 text-xs text-slate-500">{p[1]}</p><div className="mt-5 flex gap-3"><span className="rounded-full border border-white/10 px-3 py-1 text-[10px] text-slate-400">{p[2]}</span><span className="rounded-full border border-gold-500/20 px-3 py-1 text-[10px] text-gold-400">★ {p[3]}</span></div><p className="mt-5 text-xs font-bold uppercase tracking-wider text-gold-400">{p[4]} Specialist</p><Link to="/book" className="mt-6 inline-flex items-center gap-2 text-xs font-bold text-gold-400">Book with an instructor <ArrowRight size={14} /></Link></div></article>)}</div></section>
  {/* 3 */}<section className="border-y border-white/5 bg-white/[0.015]"><div className="mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-10"><div className="grid gap-5 md:grid-cols-3">{[[Award,"Certified expertise","Instructors bring structured coaching experience and clear lesson planning."],[Clock3,"Flexible availability","Select available dates and times that fit your weekly routine."],[Users,"Personal assignment","Matching considers course, transmission, schedule and learning goals."]].map(([I,t,d])=><div className="glass rounded-2xl p-7" key={t}><I className="text-gold-400" /><h3 className="mt-5 font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{d}</p></div>)}</div></div></section>
  {/* 4 */}<section className="mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-10"><div className="grid gap-8 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[0.25em] text-gold-400">Instructor Matching</p><h2 className="mt-3 text-3xl font-extrabold">The right coach makes practice more productive.</h2><p className="mt-4 text-sm leading-7 text-slate-500">During booking, choose the training type and preferred schedule. We use those details to pair the session with a suitable coaching profile and vehicle option.</p><div className="mt-7 space-y-4">{["Course specialization","Automatic or manual experience","Schedule availability","Learning pace and goals"].map(x=><div className="flex items-center gap-3 text-sm" key={x}><CheckCircle2 size={17} className="text-gold-400" />{x}</div>)}</div></div><div className="glass rounded-3xl p-8"><Star className="text-gold-400" fill="currentColor" /><p className="mt-6 text-xl font-semibold leading-8">“A great instructor should make complex decisions feel simple, repeatable and calm.”</p><p className="mt-6 text-xs text-slate-500">DriveWise coaching principle</p></div></div></section>
  {/* 5 */}<section className="border-y border-white/5 bg-white/[0.015]"><div className="mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-10"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.25em] text-gold-400">Coaching Standards</p><h2 className="mt-3 text-3xl font-extrabold">What every DriveWise coach brings to a session.</h2></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[ShieldCheck,"Safety before speed"],[Target,"Clear objectives"],[CarFront,"Practical road time"],[Zap,"Actionable feedback"]].map(([I,t])=><div className="glass rounded-2xl p-6" key={t}><I className="text-gold-400" /><h3 className="mt-4 font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-500">Each lesson stays focused on safe, useful and measurable development.</p></div>)}</div></div></section>
  {/* 6 */}<section className="mx-auto max-w-[1500px] px-5 py-20 text-center sm:px-8 lg:px-10"><p className="text-xs font-bold uppercase tracking-[0.25em] text-gold-400">Meet Your Match</p><h2 className="mx-auto mt-3 max-w-3xl text-3xl font-extrabold">Choose a course and let your coaching journey begin.</h2><Link to="/book" className="btn-gold mt-8">Book an instructor <ArrowRight size={16} /></Link></section>
</PublicLayout>; }

export function PricingPage() { const packages = [["Single Session","$129","One focused lesson","Best for a quick refresher"],["5-Session Package","$579","Save $66","Popular for steady progress"],["10-Session Package","$1,049","Save $241","Best value for full development"]]; return <PublicLayout><PageHero eyebrow="Pricing & Packages" title="Transparent pricing. Premium coaching." desc="Choose individual lessons or structured packages. Payment status and booking history remain visible in your dashboard." />
  {/* 2 */}<section className="mx-auto max-w-[1200px] px-5 py-16 sm:px-8"><div className="grid gap-5 md:grid-cols-3">{packages.map(p=><div className="glass glass-gold rounded-2xl p-7" key={p[0]}><p className="text-xs font-bold uppercase tracking-wider text-gold-400">{p[0]}</p><p className="mt-4 text-4xl font-extrabold">{p[1]}</p><p className="mt-2 text-sm text-emerald-400">{p[2]}</p><p className="mt-4 text-sm text-slate-500">{p[3]}</p><Link to="/book" className="btn-gold mt-7 w-full text-xs">Choose package</Link></div>)}</div></section>
  {/* 3 */}<section className="border-y border-white/5 bg-white/[0.015]"><div className="mx-auto max-w-[1200px] px-5 py-20 sm:px-8"><div className="grid gap-6 md:grid-cols-3">{[[CheckCircle2,"Clear package savings","Packages reduce the effective lesson cost while keeping your training plan consistent."],[Clock3,"Flexible scheduling","Use sessions around your work, study or family schedule and plan ahead."],[ShieldCheck,"No hidden coaching fees","The displayed package price is designed to make your training budget easy to understand."]].map(([I,t,d])=><div className="glass rounded-2xl p-7" key={t}><I className="text-gold-400" /><h3 className="mt-5 font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{d}</p></div>)}</div></div></section>
  {/* 4 */}<section className="mx-auto max-w-[1200px] px-5 py-20 sm:px-8"><div className="grid gap-8 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[0.25em] text-gold-400">What Your Package Covers</p><h2 className="mt-3 text-3xl font-extrabold">More than time behind the wheel.</h2><p className="mt-4 text-sm leading-7 text-slate-500">Each session is structured around a practical objective, instructor feedback and a next-step recommendation.</p><ul className="mt-7 space-y-4">{["Instructor-led practical coaching","Course-specific lesson objectives","Progress reviews between sessions","Automatic or manual training options","Booking and payment status tracking"].map(x=><li className="flex gap-3 text-sm" key={x}><CheckCircle2 size={17} className="mt-0.5 text-gold-400" />{x}</li>)}</ul></div><div className="glass rounded-3xl p-8"><Award className="text-gold-400" /><h3 className="mt-5 text-xl font-bold">Best value for long-term progress</h3><p className="mt-3 text-sm leading-7 text-slate-500">If you are preparing for a test, returning to driving or developing advanced confidence, a multi-session package gives you more room to practice and reinforce habits.</p></div></div></section>
  {/* 5 */}<section className="border-y border-white/5 bg-white/[0.015]"><div className="mx-auto max-w-[1200px] px-5 py-20 sm:px-8"><h2 className="text-3xl font-extrabold">Payment & booking process</h2><div className="mt-10 grid gap-4 md:grid-cols-4">{[["01","Choose","Select your course or package."],["02","Schedule","Pick an instructor, date and time."],["03","Pay","Review your reservation and complete payment."],["04","Track","Manage status and upcoming sessions in your dashboard."]].map(([n,t,d])=><div className="glass rounded-2xl p-6" key={n}><span className="text-xs font-bold text-gold-400">{n}</span><h3 className="mt-4 font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{d}</p></div>)}</div><p className="mt-8 text-xs leading-6 text-slate-500">The current frontend demonstrates payment status and receipt handling. Connect your production payment provider through the backend before accepting real transactions.</p></div></section>
  {/* 6 */}<section className="mx-auto max-w-[1200px] px-5 py-20 text-center sm:px-8"><p className="text-xs font-bold uppercase tracking-[0.25em] text-gold-400">Invest in Better Driving</p><h2 className="mx-auto mt-3 max-w-3xl text-3xl font-extrabold">Select the pace that works for you and start building better habits.</h2><Link to="/book" className="btn-gold mt-8">Reserve your package <ArrowRight size={16} /></Link></section>
</PublicLayout>; }

export function ContactPage() { return <PublicLayout><PageHero eyebrow="Concierge & Enquiry" title="Let's plan your next session." desc="Send an enquiry, request a callback or visit the DriveWise Executive Center." image="https://images.pexels.com/photos/30195132/pexels-photo-30195132.jpeg?auto=compress&cs=tinysrgb&w=1400" />
  {/* 2 */}<section className="mx-auto max-w-[1500px] px-5 py-16 sm:px-8 lg:px-10"><div className="grid gap-5 md:grid-cols-3">{[[Phone,"Concierge","+1 555 018 2026"],[Mail,"Email","hello@drivewiseacademy.com"],[Clock3,"Hours","Mon–Sat · 08:00 AM–07:00 PM"]].map(([I,t,v])=><div className="glass rounded-2xl p-6" key={t}><I className="text-gold-400" /><h3 className="mt-4 font-bold">{t}</h3><p className="mt-2 text-sm text-slate-500">{v}</p></div>)}</div></section>
  {/* 3 */}<section className="mx-auto grid max-w-[1500px] gap-6 px-5 pb-20 sm:px-8 lg:grid-cols-[0.8fr_1.2fr] lg:px-10"><div className="space-y-5"><div className="glass rounded-2xl p-6"><MapPin className="text-gold-400" /><h3 className="mt-4 font-bold">DriveWise Executive Center</h3><p className="mt-2 text-sm leading-6 text-slate-500">Downtown · Convenient access for students, professionals and executive clients.</p></div><div className="glass overflow-hidden rounded-2xl p-3"><iframe title="DriveWise Executive Center map" src="https://www.google.com/maps?q=Downtown&output=embed" className="h-72 w-full rounded-xl border-0 sm:h-80" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /><div className="flex items-center justify-between gap-4 px-2 py-3"><p className="text-sm text-slate-500">DriveWise Executive Center · Downtown</p><a href="https://www.google.com/maps/search/?api=1&query=Downtown" target="_blank" rel="noreferrer" className="text-sm font-bold text-gold-400">Open in Maps</a></div></div></div><div className="glass rounded-2xl p-6 sm:p-8"><h2 className="text-2xl font-bold">Send an enquiry</h2><p className="mt-2 text-sm text-slate-500">Tell us your driving goal, preferred transmission and ideal schedule. Our concierge team will follow up with your preferred contact method.</p><form onSubmit={e=>{e.preventDefault();alert("Thank you. Your enquiry has been recorded.");}} className="mt-7 grid gap-5 sm:grid-cols-2"><label><span className="mb-2 block text-xs font-semibold text-slate-400">Name</span><input required className="executive-input" placeholder="Your name" /></label><label><span className="mb-2 block text-xs font-semibold text-slate-400">Email</span><input required type="email" className="executive-input" placeholder="you@example.com" /></label><label><span className="mb-2 block text-xs font-semibold text-slate-400">Phone</span><input required className="executive-input" placeholder="Phone number" /></label><label><span className="mb-2 block text-xs font-semibold text-slate-400">Preferred course</span><select className="executive-input"><option>Beginner</option><option>Advanced</option><option>Refresher</option><option>Automatic</option><option>Manual</option></select></label><label className="sm:col-span-2"><span className="mb-2 block text-xs font-semibold text-slate-400">Enquiry</span><textarea required rows="5" className="executive-input resize-none" placeholder="Tell us what you need..." /></label><label className="sm:col-span-2 flex items-center gap-3 text-xs text-slate-500"><input type="checkbox" /> Please call me back</label><button className="btn-gold sm:col-span-2">Submit enquiry <ArrowRight size={15} /></button></form></div></section>
  {/* 4 */}<section className="border-y border-white/5 bg-white/[0.015]"><div className="mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-10"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.25em] text-gold-400">Before You Contact Us</p><h2 className="mt-3 text-3xl font-extrabold">Have these details ready for a faster recommendation.</h2></div><div className="mt-10 grid gap-4 md:grid-cols-4">{[[CarFront,"Transmission","Automatic or manual"],[Target,"Experience","New, licensed or refresher"],[Clock3,"Availability","Preferred days and times"],[MapPin,"Location","Where you usually drive"]].map(([I,t,d])=><div className="glass rounded-2xl p-6" key={t}><I className="text-gold-400" /><h3 className="mt-4 font-bold">{t}</h3><p className="mt-2 text-sm text-slate-500">{d}</p></div>)}</div></div></section>
  {/* 5 */}<section className="mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-10"><div className="grid gap-6 lg:grid-cols-3">{[["How quickly will you reply?","Concierge enquiries are reviewed as part of the academy follow-up process."],["Can I request a callback?","Yes. Select the callback option in the enquiry form and include your preferred contact details."],["Can I book directly?","Yes. Use the online booking flow to select a course, instructor, date and time."]].map(([q,a])=><div className="glass rounded-2xl p-7" key={q}><h3 className="font-bold">{q}</h3><p className="mt-3 text-sm leading-7 text-slate-500">{a}</p></div>)}</div></section>
  {/* 6 */}<section className="mx-auto max-w-[1500px] px-5 pb-20 text-center sm:px-8"><p className="text-xs font-bold uppercase tracking-[0.25em] text-gold-400">Prefer to book now?</p><h2 className="mx-auto mt-3 max-w-3xl text-3xl font-extrabold">Skip the enquiry and reserve an available session online.</h2><Link to="/book" className="btn-gold mt-8">Book a session <ArrowRight size={16} /></Link></section>
</PublicLayout>; }
