import { Link } from "react-router-dom";
import { ArrowRight, Award, CarFront, CheckCircle2, Clock3, ShieldCheck, Target, Users, Zap } from "lucide-react";
import PublicLayout from "../components/PublicLayout";
const services=[
 ["1:1 Driving Lessons","Personal coaching for beginners, licensed drivers and anyone rebuilding road confidence.","https://images.pexels.com/photos/11758756/pexels-photo-11758756.jpeg?auto=compress&cs=tinysrgb&w=1600"],
 ["Automatic Training","Smooth control, parking, lane discipline and confident city/highway driving.","https://images.pexels.com/photos/9452104/pexels-photo-9452104.jpeg?auto=compress&cs=tinysrgb&w=1400"],
 ["Manual Training","Clutch control, gear selection, hill starts and practical traffic technique.","https://images.pexels.com/photos/9827417/pexels-photo-9827417.jpeg?auto=compress&cs=tinysrgb&w=1400"],
 ["Defensive Driving","Hazard awareness, anticipation, safe following distance and risk management.","https://images.pexels.com/photos/16763244/pexels-photo-16763244.jpeg?auto=compress&cs=tinysrgb&w=1400"],
 ["Advanced Coaching","Precision control, highway confidence and refined decision-making for experienced drivers.","https://images.pexels.com/photos/5976646/pexels-photo-5976646.jpeg?auto=compress&cs=tinysrgb&w=1400"],
 ["Executive Driver Coaching","Flexible premium sessions designed around demanding schedules and polished road presence.","https://images.pexels.com/photos/11758756/pexels-photo-11758756.jpeg?auto=compress&cs=tinysrgb&w=1600"]
];
function Rail(){return <div className="mt-10 flex snap-x gap-4 overflow-x-auto pb-3">{services.map(([t,,img])=><div className="w-[78vw] shrink-0 snap-start overflow-hidden rounded-2xl sm:w-80" key={t}><img src={img} alt={t} className="h-48 w-full object-cover" onError={(e)=>{e.currentTarget.style.display="none"}}/></div>)}</div>}
export default function ServicesPage(){return <PublicLayout><section className="public-page-hero relative overflow-hidden"><div className="absolute inset-0"><img src={services[5][2]} alt="" className="h-full w-full object-cover opacity-25"/><div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/90 to-slate-950/60"/></div><div className="relative mx-auto max-w-[1500px] px-5 py-24 sm:px-8 lg:px-10"><p className="text-xs font-bold uppercase tracking-[.3em] text-gold-400">DriveWise Services</p><h1 className="mt-4 max-w-4xl text-5xl font-extrabold sm:text-6xl">Coaching services designed around real driving.</h1><p className="mt-5 max-w-2xl text-sm leading-7 text-slate-300">Choose a focused service or combine pathways into a structured training plan. Every service is built around practical outcomes and safe habits.</p><Rail/></div></section>
<section className="mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-10"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.map(([t,d,img])=><article className="glass overflow-hidden rounded-2xl" key={t}><img src={img} alt={t} className="h-52 w-full object-cover" onError={(e)=>{e.currentTarget.style.display="none"}}/><div className="p-6"><h2 className="text-xl font-bold">{t}</h2><p className="mt-3 text-sm leading-7 text-slate-500">{d}</p><Link to="/book" className="mt-6 inline-flex items-center gap-2 text-xs font-bold text-gold-400">Book this service <ArrowRight size={14}/></Link></div></article>)}</div></section>
<section className="border-y border-white/5 bg-white/[.015]"><div className="mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-10"><p className="text-xs font-bold uppercase tracking-[.25em] text-gold-400">Service Promise</p><h2 className="mt-3 text-3xl font-extrabold">What you can expect from every service.</h2><div className="mt-10 grid gap-4 md:grid-cols-4">{[[ShieldCheck,"Safety-led"],[Target,"Goal focused"],[Users,"Personal"],[Clock3,"Flexible"]].map(([I,t])=><div className="glass rounded-2xl p-6" key={t}><I className="text-gold-400"/><h3 className="mt-4 font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-500">A consistent coaching standard across every DriveWise session.</p></div>)}</div></div></section>
<section className="mx-auto max-w-[1500px] px-5 py-20 sm:px-8 lg:px-10"><div className="grid gap-8 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-gold-400">How We Build Your Plan</p><h2 className="mt-3 text-3xl font-extrabold">Start with the need, then build the right service mix.</h2><div className="mt-8 space-y-4">{["Assess your current experience","Select transmission and driving goals","Match you with a suitable instructor","Schedule sessions at useful intervals","Review progress and adjust the pathway"].map(x=><div className="flex gap-3 text-sm" key={x}><CheckCircle2 size={17} className="mt-0.5 text-gold-400"/>{x}</div>)}</div></div><div className="glass overflow-hidden rounded-3xl"><img src={services[3][2]} alt="Defensive driving" className="h-full min-h-[380px] w-full object-cover"/></div></div></section>
<section className="border-y border-white/5 bg-white/[.015]"><div className="mx-auto max-w-[1200px] px-5 py-20 sm:px-8"><div className="grid gap-5 md:grid-cols-3">{[[Award,"Certified coaching","Experienced instructors with clear lesson structures and practical feedback."],[Zap,"Flexible scheduling","Choose available dates and times that work around your commitments."],[CarFront,"Practical vehicles","Training options cover automatic and manual driving needs."]].map(([I,t,d])=><div className="glass rounded-2xl p-7" key={t}><I className="text-gold-400"/><h3 className="mt-5 font-bold">{t}</h3><p className="mt-2 text-sm leading-7 text-slate-500">{d}</p></div>)}</div></div></section>
<section className="mx-auto max-w-[1200px] px-5 py-20 text-center sm:px-8"><p className="text-xs font-bold uppercase tracking-[.25em] text-gold-400">Ready When You Are</p><h2 className="mx-auto mt-3 max-w-3xl text-3xl font-extrabold">Choose your service and reserve your next session.</h2><Link to="/book" className="btn-gold mt-8">Book a service <ArrowRight size={16}/></Link></section>
</PublicLayout>}
